--- @type { [1]: string, [2]: string|string[]|function?, [3]: function?, [4]: function? }[]
return {
	{ "1", "1Password" },
	{ "b", { "Firefox", "Google Chrome", "Vivaldi", "Safari", "Opera", "Microsoft Edge" } },
	{ "c", "Calendar" },
	{ "d", "Dash" },
	{ "e", "Mail" },
	{ "f", "Figma" },
	{ "g", "Google Chrome" },
	{ "h", require "hyperr.hammerspoon" },
	{ "l", require "hyperr.timemator" },
	{ "m", { "Messages", "Telegram", "WhatsApp", "Discord", "Element", "Messenger", "Slack" } },
	{ "n", { "Notion", "Notes" } },
	{ "p", "Spotify" },
	{ "s", { "Slack" } },
	{ "t", { "WezTerm", "iTerm 2", "Kitty" } },
	{ "u", "Due" },
	{ "v", { "ClearVPN", "NordVPN", "Surfshark" } },
	{ "w", "Neovide" },
	{ "x", require "hyperr.agenda" },
	{ "z", "zoom.us" },
}
